# ~/.streamlit/config.toml

[theme]
primaryColor="#00FF00"  # Green color for primary elements
backgroundColor="#000000"  # Black background for main content area
secondaryBackgroundColor="#333333"  # Dark grey background for sidebar and other secondary areas
textColor="#FFFFFF"  # White color for text
font = "sans serif"  # Font style (optional)


